### ISSUE TITLE
Automate moving appointments to completed appointments after date passes

### ISSUE THREAD

**Issue by jweiss0** [DangItJason/TutorBase#30]
When a meeting is completed, it should automatically be moved from the appts to the completed_appts attribute in the User model.  This may involve using some job scheduling library for Node.

**Comment by cjreed121** [comment]
In client meetings in app.js in the server I added this functionality. Right now the models and db are not aligned so this does not work fully. Once they are aligned then full testing can be done on this which is why it is commented out right now. It uses a cron job to schedule every 15 minutes and runs through all users and appointments to compare that date to current date.

**Comment by jweiss0** [comment]
No longer relevant
